### ISSUE TITLE
Player name placeholder confusion

### ISSUE THREAD

**Issue by hypews2020** [darbyjack/VoteParty#25]
I am using VoteParty to give out VoteKeys when my server reaches 50 votes. Currently, it is not doing that. 
          command: crate givekey %player_name% voting 1
That is the command I am using and my console gives this message
![image](https://user-images.githubusercontent.com/64762762/82494669-d8923100-9ae1-11ea-8f41-e55350399564.png)
I don't know what to do here

**Comment by darbyjack** [comment]
Ensure you have the Player expansion from PAPI downloaded.
https://wiki.helpch.at/glares-plugins/voteparty#setup
