### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by LuluxClient** [darbyjack/VoteParty#42]
Spigot name: xdLulux
Version : 1.16.5
Plugin version : 2.26

I was wondering if you could add a placeholder where it will tell you when you can vote again and a config where it will send a message / command to the user every time he can vote

**Comment by BlitzOffline** [comment]
This really isn't a job for VoteParty. The plugin doesn't hook into any voting websites. It is up to the website to let you know when you can vote again and some do some don't.

**Comment by BlitzOffline** [comment]
This can probably be marked as solved @darbyjack 

Commit that solved it: f6bba5dd9056c61fe11c50feace2bfcf454363ab

**Comment by darbyjack** [comment]
Solved via https://github.com/darbyjack/VoteParty/commit/f6bba5dd9056c61fe11c50feace2bfcf454363ab
