### ISSUE TITLE
Improvement proposal

### ISSUE THREAD

**Issue by DjeyMute** [darbyjack/VoteParty#46]
Hi, I have a suggestion for the plugin ! :)

My team and me had an idea.
Add a Placeholder option that lets you know how many times the VoteParty has been triggered during the day.
Do you think this is a good idea?

**Comment by BlitzOffline** [comment]
Hmm. I was thinking. what if all of the votepartys were saved to a file. well just the timestamps. right? like user votes. and you could get. votepartys daily, monthly, etc. just like the votes for a player. that would be pretty nice. you could save all of this in votes.yml? under a `votepartys:` option maybe?

**Comment by DjeyMute** [comment]
I am French so I have trouble understanding.
I'm not very good at plugins too.
I am just proposing an addition on your plugin which could be nice to me with a placeholder variable to be able to retrieve this number.

**Comment by BlitzOffline** [comment]
yes. I was just leaving a message for darbyjack. I would probably need his approval if I were to implement this.

**Comment by DjeyMute** [comment]
Okay, thank you for taking the time to answer me.
I could know on this topic if my idea is accepted?
